server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
  cloud:
    config:
      import-check:
        enabled: false
    enabled: false
  import:
    optional:  configserver:instead

  redis:
    host: localhost
    port: 6379

#spring:
#  application:
#    name: OPERACION
#  config:
#    import: optional:configserver:http://localhost:8093/

